import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // --- Light mode semantic tokens (Ember palette) ---
        background: "#FAF7F2",
        "on-background": "#171311",
        surface: "#FAF7F2",
        "surface-lowest": "#FFFFFF",
        "surface-low": "#F2EDE4",
        "surface-container": "#F2EDE4",
        "surface-high": "#E6E0D5",
        "surface-highest": "#DBD6CA",
        "surface-variant": "#DBD6CA",
        "on-surface": "#171311",
        "on-surface-variant": "#5A554D",
        "surface-dim": "#DBD6CA",
        "inverse-surface": "#2E2926",
        "inverse-on-surface": "#FAF7F2",
        "surface-tint": "#F26B1F",
        outline: "#8F8A82",
        "outline-variant": "#E6E0D5",

        // --- Dark mode semantic tokens (use with dark: prefix, Ember dark) ---
        "d-background": "#0B0B0E",
        "d-on-background": "#FFFFFF",
        "d-surface": "#16161C",
        "d-surface-lowest": "#0B0B0E",
        "d-surface-low": "#16161C",
        "d-surface-container": "#1F1F27",
        "d-surface-high": "#2C2C36",
        "d-surface-highest": "#353540",
        "d-surface-variant": "#2C2C36",
        "d-on-surface": "#FFFFFF",
        "d-on-surface-variant": "#B5B8C0",
        "d-outline": "#7A7E88",
        "d-outline-variant": "#2C2C36",

        // --- Brand / Ember palette tokens ---
        primary: "#F26B1F",
        "on-primary": "#FFFFFF",
        "primary-container": "#C24E0D",
        "on-primary-container": "#FFE6CF",
        "primary-fixed": "#FFE6CF",
        "primary-fixed-dim": "#FFC56B",
        "on-primary-fixed": "#3D1800",
        "on-primary-fixed-variant": "#F26B1F",
        "inverse-primary": "#C24E0D",
        secondary: "#3EBB7F",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#CFEBDF",
        "on-secondary-container": "#1A5C3A",
        "secondary-fixed": "#CFEBDF",
        "secondary-fixed-dim": "#3EBB7F",
        "on-secondary-fixed": "#0A2E1D",
        "on-secondary-fixed-variant": "#2A8A5A",
        tertiary: "#FFC56B",
        "on-tertiary": "#3D2800",
        "tertiary-container": "#E4A23A",
        "on-tertiary-container": "#3D2800",
        "tertiary-fixed": "#FFE6CF",
        "tertiary-fixed-dim": "#FFC56B",
        "on-tertiary-fixed": "#3D2800",
        "on-tertiary-fixed-variant": "#C24E0D",
        error: "#FF5A5A",
        "on-error": "#FFFFFF",
        "error-container": "#FFDDDD",
        "on-error-container": "#7A0000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        unit: "4px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        sans: ["Manrope", "ui-sans-serif", "system-ui"],
        display: ['"Space Grotesk"', "Manrope", "system-ui"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "0", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "0", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
