import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0B0B0E",
        "on-background": "#FFFFFF",
        surface: "#16161C",
        "surface-container-lowest": "#080808",
        "surface-container-low": "#111118",
        "surface-container": "#16161C",
        "surface-container-high": "#1F1F27",
        "surface-container-highest": "#27272F",
        "surface-high": "#1F1F27",
        "surface-highest": "#27272F",
        "surface-dim": "#0B0B0E",
        "surface-variant": "#1F1F27",
        "surface-tint": "#F26B1F",
        "on-surface": "#FFFFFF",
        "on-surface-variant": "#B5B8C0",
        primary: "#F26B1F",
        "primary-container": "#C45A18",
        "on-primary": "#ffffff",
        "on-primary-container": "#FFD4B0",
        "primary-fixed": "#3A1E0A",
        "primary-fixed-dim": "#5A2E12",
        "inverse-primary": "#F26B1F",
        secondary: "#3EBB7F",
        "secondary-container": "#1A4A35",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#3EBB7F",
        "secondary-fixed": "#8BE0B8",
        "secondary-fixed-dim": "#5ECE99",
        "on-secondary-fixed": "#0B2C1F",
        "on-secondary-fixed-variant": "#1A4A35",
        tertiary: "#E5A84A",
        "tertiary-container": "#8A5A20",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#FFC56B",
        "tertiary-fixed": "#3A2205",
        "tertiary-fixed-dim": "#7A4F1A",
        "on-tertiary-fixed": "#FFE8C0",
        "on-tertiary-fixed-variant": "#E5A84A",
        outline: "#7A7E88",
        "outline-variant": "#2C2C36",
        "inverse-surface": "#E0E0E8",
        "inverse-on-surface": "#0B0B0E",
        error: "#FF5A5A",
        "error-container": "#3D1A1A",
        "on-error": "#ffffff",
        "on-error-container": "#FF9999",
        // Per-habit accent spectrum, mirrored from the app's habit visuals
        // (lib/data/habit-images.ts) for mockups and feature illustrations.
        "habit-walk": "#5DBB63",
        "habit-run": "#4DB6AC",
        "habit-water": "#4FB9E8",
        "habit-read": "#C7A7FF",
        "habit-meditate": "#8EC5FF",
        "habit-sleep": "#A9B7FF",
        "habit-journal": "#E7B980",
        "habit-code": "#63D2B4",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        display: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        unit: "4px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        gutter: "16px",
      },
      boxShadow: {
        card: "0 4px 24px rgba(0,0,0,0.4)",
        "card-hover": "0 12px 36px rgba(0,0,0,0.55)",
        nav: "0 2px 20px rgba(0,0,0,0.3)",
        cta: "0 8px 28px rgba(242,107,31,0.38)",
        "cta-hover": "0 12px 40px rgba(242,107,31,0.5)",
        sidebar: "4px 0 20px rgba(0,0,0,0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
